# Build the manager binary
FROM servicefabrikjenkins/service-fabrik-broker:0.22.0

WORKDIR .
COPY data-access-layer/eventmesh/src/ApiServerClient.js /opt/service-fabrik-broker/broker/data-access-layer/eventmesh/src/ApiServerClient.js
