# Build the manager binary
FROM servicefabrikjenkins/service-fabrik-broker:0.22.0

WORKDIR /opt/service-fabrik-broker/broker
COPY broker/data-access-layer/eventmesh/src/ApiServerClient.js data-access-layer/eventmesh/src/ApiServerClient.js
